### ISSUE TITLE
Having issues with mixins in 1.14.2 (Also 1.14.3)

### ISSUE THREAD

**Issue by ThatJigsaw** [NuggetMC/CraftNugget#22]
I really want to work on a mod for craftnugget. but i have some problems with it.
i made more than 30 builds of a simple mod just to test if i can fix that issue. i never managed to load the test server/client successfully. i also tried to clear the gradle cash but that didn't worked either.

The latest project file is attached to this comment.
-ThatJigsaw (AKA CODY_AI)
[EssentialsG - a1.0.2_b01.zip](https://github.com/NuggetMC/CraftNugget/files/3250697/EssentialsG.-.a1.0.2_b01.zip)

**Comment by DeathsGun** [comment]
What i can say so far is that the mappings wasn't compatible we didn't update to `
yarn_mappings=1.14.2+build.7` so there to many changes the classes so it crashed.
I am currently updating to these mappings and test your mod

**Comment by DeathsGun** [comment]
ok got it to work but your project has some wrong mixins but it does all load. I will now publish the fix and so travis release it. So you can say if you problem was so i can close this

**Comment by DeathsGun** [comment]
this version uses the latest `1.14.2` mappings not but not tested with `1.14.3-pre1`

`modCompile "tk.nuggetmc:craftnugget:1.1.2-206.1"`
I will also update the example mod
